BASE_PATH = '/Users/karuhanga/Projects/FYProject/Elizet/libs/deep_speech/models/'
MODEL_PATH = BASE_PATH + 'output_graph.pbmm'
ALPHABET_PATH = BASE_PATH + 'alphabet.txt'
LANGUAGE_MODEL = BASE_PATH + 'lm.binary'
TRIE = BASE_PATH + 'trie'
